# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-13 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcpp_follow', '0002_auto_20171013_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklist',
            name='subject_identifier',
            field=models.CharField(max_length=50, unique=True, verbose_name='Subject Identifier'),
        ),
    ]
